### ISSUE TITLE
2018-12-17 Microservices Monday

### ISSUE THREAD

**Issue by south37** [wantedly/microservices_monday#27]
2018-12-17 19:00~20:00

Microservices Mondayは、マイクロサービスに関連する話を気軽に共有する会です。毎週月曜日に開催されます。

社外からの参加を想定しているため、レポジトリはpublicになっています。

次のようなポリシーを掲げて開催しています。

- 事前の準備をがんばらない
- 途中参加・途中退席は自由
- 毎週やる

話したい・聞きたいネタを書いていきます ✏️

ネタに困ったときは

- Kubecon/CloudNativeCon のリストを眺める
- [Microservice Weekly](https://microserviceweekly.com/) を眺める

ハッシュタグ [#microservices_monday](https://twitter.com/hashtag/microservices_monday?src=hash)

**Comment by south37** [comment]
etcd の cluster upgrade by @potsbo

**Comment by izumin5210** [comment]
「サービス間でDB共有するのはなんでダメなんだっけ」

**Comment by izumin5210** [comment]
https://microservices.io/patterns/data/database-per-service.html

**Comment by south37** [comment]
[マイクロサービスアーキテクチャ](https://www.oreilly.co.jp/books/9784873117607/) の 4.3 章「共有データベース」でもDB共有のアンチパターンについて説明されてます。

**Comment by izumin5210** [comment]
saga pattern

https://microservices.io//microservices/general/2018/11/08/mucon.html
https://microservices.io/patterns/data/saga.html

**Comment by Altech** [comment]
ガウディ本のまえがきが良いことが書いてある話

**Comment by izumin5210** [comment]
ガウディ本 https://www.amazon.co.jp/%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%82%BF%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AE%E6%A6%82%E5%BF%B5%E3%83%BB%E6%8A%80%E6%B3%95%E3%83%BB%E3%83%A2%E3%83%87%E3%83%AB-Architects-Archive%E3%82%AF%E3%83%A9%E3%82%B7%E3%83%83%E3%82%AF%E3%83%A2%E3%83%80%E3%83%B3%E3%83%BB%E3%82%B3%E3%83%B3%E3%83%94%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0-%E3%82%BB%E3%82%A4%E3%83%95%E3%83%BB%E3%83%8F%E3%83%AA%E3%83%87%E3%82%A3/dp/4798113468

**Comment by izumin5210** [comment]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.102.7366&rep=rep1&type=pdf

**Comment by dulltz** [comment]
@potsbo 
先週のKubeConでもetcd アップグレードの話ありました

マイナーバージョンをひとつずつ上げろ、ローリングアップデートしろ、っていう話だったはず
https://kccna18.sched.com/event/JAo2/deep-dive-etcd-xiang-li-alibaba-wenjia-zhang-google

詳細はこちら（よんでない
https://github.com/etcd-io/etcd/tree/master/Documentation/upgrades

**Comment by luvtechno** [comment]
next -> [2019\-01\-07 Microservices Monday · Issue \#28 · wantedly/microservices\_monday](https://github.com/wantedly/microservices_monday/issues/28)

**Comment by luvtechno** [comment]
次回は年明けです！
