### ISSUE TITLE
2019-01-15 Microservices Monday

### ISSUE THREAD

**Issue by creasty** [wantedly/microservices_monday#29]
Microservices Mondayは、マイクロサービスに関連する話を気軽に共有する会です。毎週月曜日に開催されます。

社外からの参加を想定しているため、レポジトリはpublicになっています。

次のようなポリシーを掲げて開催しています。

- 事前の準備をがんばらない
- 途中参加・途中退席は自由
- 毎週やる

話したい・聞きたいネタを書いていきます ✏️

ネタに困ったときは

- Kubecon/CloudNativeCon のリストを眺める
- [Microservice Weekly](https://microserviceweekly.com/) を眺める

ハッシュタグ [#microservices_monday](https://twitter.com/hashtag/microservices_monday?src=hash)

**Comment by creasty** [comment]
write APIs using direct SQL queries with no hassle, let's rethink about SQL
https://github.com/alash3al/sqler

**Comment by izumin5210** [comment]
sqler 気になってたやつ 👀 
サマリが楽しみｗ

**Comment by rerost** [comment]
## Argo
- https://github.com/rerost?tab=repositories
  - [Argo によるコンテナネイティブなデータパイプラインのワークフロー管理 - LIVESENSE Data Analytics Blog](https://analytics.livesense.co.jp/entry/2018/07/24/110000)
  - [Open source container-native workflow engine for Kubernetes. \| argo](https://argoproj.github.io/docs/argo/demo.html)

## Failure Injection
- [LinkedOut: A Request-Level Failure Injection Framework \| LinkedIn Engineering](https://engineering.linkedin.com/blog/2018/05/linkedout--a-request-level-failure-injection-framework)

## Data Pipeline
- [GCPでStreamなデータパイプライン始めました - Mercari Engineering Blog](https://tech.mercari.com/entry/2018/12/03/162618)
- Netflix, Uber, Spotifyのデータパイプラインの変遷
  - [Evolution of the Netflix Data Pipeline – Netflix TechBlog – Medium](https://medium.com/netflix-techblog/evolution-of-the-netflix-data-pipeline-da246ca36905)
  - [Uber's Big Data Platform: 100+ Petabytes with Minute Latency \| Uber Engineering Blog](https://eng.uber.com/uber-big-data-platform/)
  - [Spotify’s Event Delivery – The Road to the Cloud (Part I) \| Labs](https://labs.spotify.com/2016/02/25/spotifys-event-delivery-the-road-to-the-cloud-part-i/)
- [Reliable export of Cloud Pub/Sub streams to Cloud Storage \| Labs](https://labs.spotify.com/2017/04/26/reliable-export-of-cloud-pubsub-streams-to-cloud-storage/)
- [Autoscaling Pub/Sub Consumers \| Labs](https://labs.spotify.com/2017/11/20/autoscaling-pub-sub-consumers/)
- [System Architectures for Personalization and Recommendation](https://medium.com/netflix-techblog/system-architectures-for-personalization-and-recommendation-e081aa94b5d8)

**Comment by bgpat** [comment]
https://speakerdeck.com/capsmalt/k8sjp-number-15-kubecon-recap-harbor-and-dragonfly-by-capsmalt

**Comment by S-YOU** [comment]
[Google Cloud Production Guideline
](https://medium.com/google-cloud/production-guideline-9d5d10c8f1e)
