### ISSUE TITLE
2019-02-04 Microservices Monday

### ISSUE THREAD

**Issue by rerost** [wantedly/microservices_monday#32]
2018-02-04 19:00~20:00

Microservices Mondayは、マイクロサービスに関連する話を気軽に共有する会です。毎週月曜日に開催されます。

社外からの参加を想定しているため、レポジトリはpublicになっています。

次のようなポリシーを掲げて開催しています。

- 事前の準備をがんばらない
- 途中参加・途中退席は自由
- 毎週やる

話したい・聞きたいネタを書いていきます ✏️

ネタに困ったときは

- Kubecon/CloudNativeCon のリストを眺める
- [Microservice Weekly](https://microserviceweekly.com/) を眺める

ハッシュタグ [#microservices_monday](https://twitter.com/hashtag/microservices_monday?src=hash)

**Comment by bgpat** [comment]
https://medium.com/memory-leak/5-microservices-trends-to-watch-in-2018-aed135f70e51

**Comment by potsbo** [comment]
https://www.botmetric.com/blog/top-five-devops-noops-trends-watch-2017-beyond/

**Comment by koudaiii** [comment]
https://robinhood.engineering/how-we-built-a-better-news-system-8c30b77067bc 株をする上で News は超貴重なデータだからリアルタイムで取れるように steraming で配信する基盤。シンプルな上にスケールしやすい基盤ですごい。

**Comment by potsbo** [comment]
https://aws.amazon.com/jp/blogs/news/new-tls-termination-for-network-load-balancers/

**Comment by koudaiii** [comment]
https://blog.houzz.com/migration-to-redis-cluster/ インテリアのデータが増えまくるから、 その分 cache もスケールに出来るように Redis Cluster を作って運用する。

**Comment by koudaiii** [comment]
https://www.cbinsights.com/research-unicorn-companies

**Comment by south37** [comment]
https://github.com/containernetworking/cni

**Comment by koudaiii** [comment]
コンテナネットワーキング（CNI）最前線
https://www.slideshare.net/motonorishindo/cni-124981353

**Comment by bgpat** [comment]
https://github.com/aws/amazon-vpc-cni-k8s

**Comment by south37** [comment]
https://github.com/aws/amazon-ecs-cni-plugins
